export type SpeakerType = {
  id: string;
  name: string;
  designation?: string;
  university?: string;
  bio: string;
  imageUrl:string;
  about?:string;
  title?:string;
  onClick?:() => void;
};
export const speakers: SpeakerType[] = [
  {
    id: "1",
    designation:"Director of Doctor of Engineering.",
    university:"Johns Hopkins University",
    name: "Dr.Ashutosh Dutta",
    bio: "Ashutosh Dutta is Chief 5G Strategist and APL Fellow at Johns Hopkins University’s Applied Physics Labs, USA. He serves as the director of Doctor of Engineering at Johns Hopkins University. In the past, he served as the chair of ECE department of Engineering for Professionals at JHU, Director of Technology Security at AT&T, CTO of Wireless at NIKSUN, Senior Scientist in Telcordia Research, Director of Central Research Facility at Columbia University, and Computer Engineer with TATA Motors. He has authored more than 110 technical papers, one book published by John and Wiley, and 5 book chapters, and has 31 issued patents. Ashutosh is recipient of IEEE MGA’s 2009 Leadership Award, IEEE-USA’s 2010 Professional Leadership Award, 2022 IEEE-USA George F. McClure Citation of Honor and 2022 IEEE North American Region Exceptional Service Award. Ashutosh served as Member-At-Large for IEEE Communications Society for 2020-2025 and Distinguished Lecturer from 2018-2021. Ashutosh was inducted into Internet IPV6 Hall of Famer in 2024. He co-founded the IEEE STEM conference (ISEC) in 2011 and has served its Co-Chair since then. Ashutosh currently serves as the Chair for IEEE Industry Connection’s O-RAN activities and 6G. As the Founding Co-Chair of IEEE Future Networks he led technology roadmap, publications, standardization, testbed, education, industry engagement, conferences and workshops in the area of 5G and 6G, while keeping a focus on humanitarian needs. Ashutosh is a Distinguished Alumnus of NIT Rourkela with a BS in Electrical Engineering, MS in Computer Science from NJIT, and a PhD in EE from Columbia University. Ashutosh is an IEEE Fellow and an ACM Distinguished member.",
    imageUrl: "/Ashutosh.jpg",
    title:"5G/6G Security and AI/ML – Opportunities and Challenges",
    about:`Next generation cellular networks such as 5G and 6G promise to support emerging applications such as enhanced mobile broadband, mission critical applications for the first responder, remote surgery, and industrial IOT among others. While Network Function Virtualization and Software Defined Networking open up the door for programmable networks and rapid service creation, these also offer both security opportunities, and introduces additional challenges and complexities. The talk focuses on various security challenges and opportunities introduced by 5G enablers such as Hypervisor, Virtual Network Functions (VNFs), SDN controller, orchestrator, network slicing, cloud RAN, edge cloud, and virtual security function. This talk introduces threat taxonomy for 5G security from an end-to-end system perspective including, interfaces, protocols, potential threats introduced by these enablers, and associated mitigation techniques. Additionally, this talk highlights how AI/ML can help enhance security features of these networks and elaborates some adverse effects of AI/ML.  Finally, the talk introduces some of the ongoing activities within various standards communities including open source consortiums, large scale NSF testbeds, and illustrates a few deployment use case scenarios.`
    
  },
  {
    id: "2",
    name: "Dr. Balakrishna Islavath",
    designation:"Senate Member",
    university:"University of Madras and Anna University",
    bio: `Dr. I. Balakrishna is a distinguished academic and research professional, recognized for his extensive contributions to the fields of RF, Microwave, and mm-Wave technologies.Recently appointed as a Senate Member of the University of Madras and Anna University by the Hon'ble Governor of Tamil Nadu, Shri RN Ravi, Dr Balakrishna serves as an Executive Committee Member at the Center for Internet of Things (C-IoT) at Anna University,furthering innovative technological advancements. His impressive career includes leadership roles as Chairman and Board of Studies(BOS)member across prestigious institutions such as IITs, NITs, and various renownedengineeringcolleges. With a rich history as a Visiting Scientist at esteemed institutions like MIT, GeorgiaTech, and IISc Bangalore, he previously excelled as Chief Manager and Headof R&DatReliance Jio Pvt. Ltd, Mumbai. Currently, he is a dedicated Scientist at the R&D Research Centre, Chennai, Ministryof Electronics & Information Technology(MeitY), GoI. With over 15 years of hands-onexperience in R&D, he has been instrumental in executing critical national defenseprojects,contributing to the successful test flights of missiles, and solving complex electromagneticchallenges, including antenna systems for naval ships, satellites, and stealthtechnologyaircraft.His collaborative spirit has led to significant contributions to the "IndigenousDevelopment of End-to- End 5G Test Bed," a project funded by the Department ofTelecommunications (DoT), which resulted in India's first fully functional MIMOandmassive MIMO antenna systems demonstrated to the Hon’ble Prime Minister. His dedication to technology advancement is evident in his active contributionstoindigenous 5G/6G projects and future-oriented tech programs in India. His current researchinterests include a wide array of cutting-edge topics, such as:
 Advanced Communication Systems: 5G/6G solutions, Massive MIMO, andSmartMedical Applications, Spectrum Studies, RF SoC, Intelligent ReflectingSurfaces,and Jammer & Surveillance Systems
 IoT and Smart Applications: Innovations in Smart Agriculture, Smart Cities,Health Monitoring Wearables, and IoT-integrated Smart Homes
 Strategic Antenna and RF Developments: Design and optimizationof phasedarray antennas, MIMO, massive MIMO, WiGig, high-impedance surfaces, andUAV antennas
 Emerging Technologies: Airborne and autonomous applications, robotics, hybridand e- vehicles, RFICs, RF MEMs, and semiconductor technologies
 Innovative Antenna Solutions: Switched beam arrays, aperture coupledandplanarantenna arrays, RF cloaking, and metamaterial-based antennas
He is highly involved in capacity building, delivering impactful lectures, workshops, andconferences globally. He is a prolific author, with several patents and publications inIEEEInternational Journals, contributing to the academic and scientific community. His work, driven by a passion for societal impact and national advancement, resonates acrosssectors, reflecting his commitment to harnessing technology to address contemporarychallengesand enhance India's global standing in innovation.`,
    imageUrl: "/BalakrishnaIslavat.jpg",
    about:`Antenna technology is a key enabler for a wide range of next-generation technologies, including 5G evolution, 6G, IoT, and beyond.  This talk will explore the latest advancements in antenna technologies that are critical to realizing the full potential of 6G. Key topics include novel antenna designs for millimetre-wave and terahertz frequencies, massive MIMO architectures, reconfigurable intelligent surfaces (RIS), and energy-efficient antenna solutions.   The presentation will cover wideband antennas, reconfigurable antennas, massive MIMO, and innovative antenna systems. Furthermore, the talk will highlight the importance of developing sustainable antenna solutions to minimise energy consumption and promote environmentally friendly technologies, paving the way for smarter and more sustainable societal advancements.`,
    title:`Innovative Antenna Solutions for Next-Generation Technologies: Driving Smart and Sustainable Societal Advancements`
  },
  {
    id: "3",
    designation:"Prof. of Electrical and Computer Engg.",
    university:"Northeastern University(NU)",
    name: "Josep Miquel Jornet",
    bio: `Josep Miquel Jornet is Professor of Electrical and Computer Engineering at Northeastern University (NU), the Associate Dean of Research of the College of Engineering (COE), the Associate Director of the Institute for the Wireless Internet of Things (WIoT), and the Director of the Ultrabroadband Nanonetworking (UN) Laboratory. He received his Ph.D. in Electrical and Computer Engineering from the Georgia Institute of Technology, Atlanta, GA, in August 2013. His research interests are in terahertz communication networks, wireless nano-bio-communication networks, and the Internet of Nano-Things. He has co-authored more than 250 peer-reviewed scientific publications in these areas, including one book and five US patents. His work has received over 20,000 citations (h-index of 65 as of May 2025). He is serving as the lead PI on multiple grants from U.S. federal agencies, including the National Science Foundation, the Air Force Office of Scientific Research, and the Air Force Research Laboratory, and industry. He is the recipient of multiple awards, including the NSF CAREER Award in 2019, the 2022 IEEE ComSoc RCC Early Achievement Award, and the 2022 IEEE Wireless Communications Technical Committee Outstanding Young Researcher Award, among others, as well as eight best paper awards. He is a Fellow of the IEEE (Class of 2024) and served as an IEEE ComSoc Distinguished Lecturer (Class of 2022-2024). He is also the editor-in-chief of the Elsevier Nano Communication Networks journal and Editor for IEEE Transactions on Communications, IEEE Transactions on Molecular, Biological and Multi-scale Communications, and Nature Scientific Reports.`,
    imageUrl: "/JosepMiquelJorne.jpg",
    about:`The need for ever-increasing bandwidth is driving the research community to explore new spectrum frontiers. The sub-terahertz and terahertz bands (0.1–10 THz) offer a vast swath of untapped spectrum that could be used for many innovative communication and sensing applications. Additionally, the shorter wavelengths and the non-negligible photon energy of terahertz radiation open the door to innovative applications across scales. Over the last decade, remarkable progress in electronic, photonic, and plasmonic technologies has narrowed the terahertz technology gap. Moreover, in-depth studies on terahertz signal propagation, combining physics-based and data-driven approaches, have dispelled misconceptions surrounding the terahertz channel. However, several communication roadblocks must be overcome to unleash the spectrum above 100 GHz. This talk will follow a bottom-up approach to highlight innovative solutions and open challenges for terahertz communications and sensing systems on the ground, in the air, and in space. First, we delve into wavefront engineering for near-field THz links, showcasing novel beam types, including self-healing Bessel and curving Airy beams and discuss the unique opportunities these beams offer for short-range, high-capacity networks. Second, we demonstrate the advantageous role of THz frequencies in satellite communication networks, highlighting their potential for high-speed access links, and the upcoming, first-of-its-kind, TeraLink experimental mission.`,
    title:`Terahertz Communications and Sensing: From the Near Field to Space Networks`
  },
  {
    id: "4",
    name: "Kumar Vijay Mishra",
    designation:"Senior Fellow ",
    university:"United States DEVCOM Army Research Laboratory",
    bio: `Kumar Vijay Mishra is a prominent figure in the field of electrical engineering, with a focus on wireless communication and signal processing. He has made significant contributions to the development of advanced communication systems, including 5G and beyond. Dr. Mishra has published numerous research papers in top-tier journals and conferences, and holds several patents in the area of wireless technologies. He is actively involved in various professional organizations, and has served as a reviewer for leading journals in his field. His work is characterized by a strong emphasis on innovation and practical applications, making him a sought-after speaker at industry events and academic conferences.Kumar Vijay Mishra (S’08-M’15-SM’18) obtained a Ph.D. in electrical engineering and M.S. in mathematics from The University of Iowa in 2015, and M.S. in electrical engineering from Colorado State University in 2012, while working on NASA’s Global Precipitation Mission Ground Validation (GPM-GV) weather radars. He received his B. Tech. summa cum laude (Gold Medal, Honors) in electronics and communication engineering from the National Institute of Technology, Hamirpur (NITH), India in 2003. He is a Senior Fellow at the United States DEVCOM Army Research Laboratory; Research Scientist at the Institute for Systems Research, The University of Maryland, College Park under the ARL-ArtIAMAS program; Technical Adviser to Singapore-based automotive radar start-up Hertzwell and Boston-based imaging radar startup Aura Intelligent Systems; and honorary Research Fellow at SnT - Interdisciplinary Centre for Security, Reliability and Trust, University of Luxembourg. Previously, he had research appointments at the Electronics and Radar Development Establishment (LRDE), Defence Research and Development Organisation (DRDO) Bengaluru; IIHR - Hydroscience & Engineering, Iowa City, IA; Mitsubishi Electric Research Labs, Cambridge, MA; Qualcomm, San Jose; and Technion - Israel Institute of Technology.
   
Dr. Mishra is the Distinguished Lecturer of the IEEE Communications Society (2023-2024), IEEE Aerospace and Electronic Systems Society (AESS) (2023-2024), IEEE Vehicular Technology Society (2023-2024), IEEE Geoscience and Remote Sensing Society (2024-2025), and IEEE Future Networks Initiative (2022). He is the recipient of the IEEE Signal Processing Society Pierre-Simon Laplace Early Career Technical Achievement Award (2024), Special Mention for the IEEE AESS M. Barry Carlton Award (2023), IET Premium Best Paper Prize (2021), IEEE T-AES Outstanding Editor (2021, 2023), U. S. National Academies Harry Diamond Distinguished Fellowship (2018-2021), American Geophysical Union Editors' Citation for Excellence (2019), Royal Meteorological Society Quarterly Journal Editor's Prize (2017), Viterbi Postdoctoral Fellowship (2015, 2016), Lady Davis Postdoctoral Fellowship (2017), DRDO LRDE Scientist of the Year Award (2006), NITH Director’s Gold Medal (2003), and NITH Best Student Award (2003). He has received Best Paper Awards at IEEE MLSP 2019 and IEEE ACES Symposium 2019. 

Dr. Mishra is Chair (2023-2026) of the International Union of Radio Science (URSI) Commission C, Chair (2025-) of IEEE AESS Technical Working Group on Integrated Sensing and Communications (ISAC-TWG), and Vice-Chair (2021-present) of the IEEE Synthetic Aperture Standards Committee, which is the first SPS standards committee. He has been Chair (2023-2025) of the IEEE SPS Synthetic Apertures Technical Working Group. He has been an elected member of three technical committees of IEEE SPS: SPCOM, SAM, and ASPS, and IEEE AESS Radar Systems Panel. He has been Senior Area Editor of IEEE Transactions on Signal Processing (2024-), Associate Editor of IEEE Transactions on Aerospace and Electronic Systems (2020-) and IEEE Transactions on Antennas and Propagation (2023-). He has been a lead/guest editor of several special issues in journals such as IEEE Signal Processing Magazine, IEEE Journal of Selected Topics in Signal Processing, IEEE Journal on Selected Areas in Communications, and IEEE Journal of Selected Topics in Applied Earth Observations and Remote Sensing. He is the lead co-editor of several books on signal processing and radar: Signal Processing for Joint Radar-Communications (Wiley-IEEE Press, 2024), Next-Generation Cognitive Radar Systems (IET Press Electromagnetics and Radar Series, 2023), Advances in Weather Radar Volumes 1, 2 & 3 (IET Press Electromagnetics and Radar Series, 2023), and Handbook of Statistics 55: Multidimensional Signal Processing (Elsevier). His research interests include radar systems, signal processing, remote sensing, and electromagnetics. 

 


Title: Signal Processing for Integrated Sensing and Communications
Abstract: In this talk, we focus on the recent developments toward integrated sensing and communications (ISAC). We consider a broad definition of coexistence, which covers ISAC, collaborative communications, and sensing with interference. Toward fully realizing the coexistence of the two systems, optimization of resources for both new/futuristic sensing and wireless communications modalities is crucial. These synergistic approaches that exploit the interplay between state sensing and communications are both driving factors and opportunities for many current signal processing and information-theoretic techniques. In addition, a large body of prior works considers colocated ISAC systems while distributed systems remain relatively unexamined. Building on the existing approaches, the talk focuses on highlighting emerging scenarios in collaborative and distributed ISAC, particularly at mm-Wave and THz frequencies, highly dynamic vehicular/automotive environments that would benefit from information exchange between the two systems. It presents the architectures and possible methodologies for mutually beneficial distributed co-existence and co-design, including sensor fusion and heterogeneously distributed radar and communications. The talk also considers recent developments such as the deployment of intelligent reflecting surfaces (IRS) in ISAC, 5G systems, passive internet-of-things, and ISAC secrecy rate optimization. This talk aims to draw the attention of the radar, communications, and signal processing communities toward an emerging area, which can benefit from the cross-fertilization of ideas in distributed systems.

`,
imageUrl: "/KumarVijayMishra.jpg"
  },
  {
    id: "5",
    name:"Dr. Lalit Kumar Singh",
    designation:"Scientist & Head of Artificial Intelligence Applications",
    university:"NPCIL-BARC, Department of Atomic Energy, Government of India",
    bio:` Dr. Lalit Kumar Singh received his Ph.D. degree from Indian Institute of Technology (Banaras Hindu University). He is currently a Scientist & Head of Artificial Intelligence Applications in NPCIL-BARC, Department of Atomic Energy, Government of India, and has distinction of working on Pressurized Heavy Water Reactors (PHWR) and Light Water Reactors (LWR). He is also working as Adjunct Professor in IIT Gandhinagar, Visiting Professor in IIIT Gwalior & BHU and Professor of Practice in VJTI Mumbai. He has an illustrious career and succeeded in several critical jobs assigned to him in his illustrious career, though, each of them was challenging. His assignments over the years range from design, development, testing, IV&V, related research and site validation of the safety critical computer based systems of Indian Nuclear Power Plants. He has published several research papers in journals of high impact factor like IEEE Transactions, IEEE Computer, ACM, etc. He is a Senior Member of IEEE and member on the advisory Board of IEEE Industry Relations & Entrepreneurship Committee. He has been invited for chief guest, keynote speeches, session chair and talks in many international conferences, short term courses, workshops & faculty development programs from many IITs, NITs & other institutes of national importance. He is recipient of many awards like prestigious IEEE K. Shankar award, publication award, group achievement award, etc. He is a reviewer of several SCI indexed journals of high impact factor. He is a life member of Indian Nuclear Society. He is founder member and industrial coordinator of the proposed Center of Dependability at IIT(BHU). He is in the panel of faculty assessment committee for Department of CSE, IIT Roorkee to assess their research profile and give recommendations. He is a member of editorial board of many reputed journals and guest lead editor of many special issues. He is supervising many PhD students of different IITs, NITs and is PhD thesis examiner of IITs, NITs and other reputed institutes. He is an expert member of Industrial policy formation of IIT Ropar, BoS of many autonomous institutes and member on the advisory board of many institutes/universities. He is a reviewer and project collaborator of Research proposals of Board of Research in Nuclear Sciences (BRNS). He is also faculty of Nuclear Training Centre, Department of Atomic Energy, Government of India. He is interfacing with other countries, like Russia, USA, France, etc. for importing nuclear reactors that are based on new technologies. His research interests are in the area of reliability, safety and security of safety critical computer based systems. So far, he has completed 33 projects of Department of Atomic Energy, Government of India. He holds 520 rank in India in the list of World’s scientists released by AD Scientific Index.`,
    imageUrl: "/DrLalitKumarSingh.jpg",
    title:"Artificial Intelligence in Nuclear Power Plants",
    about:`This talk will explore the transformative role of Artificial Intelligence (AI) in the operation and management of Nuclear Power Plants (NPPs), focusing on its applications to enhance safety, efficiency, and sustainability. As the global demand for clean energy rises, nuclear power remains a key player in achieving low-carbon energy production. AI technologies offer substantial opportunities for improving plant performance, predictive maintenance, anomaly detection, and real-time decision-making. The presentation will cover real-world case studies where AI has been successfully integrated into various aspects of NPPs, such as: Predictive Maintenance, Safety and Security, Operational Optimization, Advanced Control Systems. Through these case studies, the talk will demonstrate how AI is driving the next generation of nuclear energy innovation. It will also highlight the challenges, ethical considerations, and future prospects of AI integration in the nuclear industry, aiming to provide a comprehensive understanding of how AI can help shape the future of nuclear energy production and contribute to the global transition to sustainable energy.`
  },
  {
    id: "6",
    name: "Shuvra S. Bhattacharya",
    designation:"Dept. of Electrical and Computer Engg.",
    university:"University of Maryland, College Park",
    bio: `Shuvra S. Bhattacharyya is a Professor in the Department of Computer Science at the University of Maryland, College Park. He is also a co-director of the Maryland Cybersecurity Center (MC2) and the Maryland Robotics Center (MRC). His research interests include computer architecture, hardware-software co-design, and cybersecurity. He has published extensively in these areas and has received several awards for his work, including the NSF CAREER Award and the IEEE TCCA Young Architect Award.`,
    imageUrl: "/SurvaSBhattacharya.jpg",
    title: "Software Synthesis from Dataflow Schedule Graphs",
    about: `In dataflow-based design processes for signal processing and machine learning (SPML), scheduling is a critical task that affects practical measures of performance, including latency, throughput, energy consumption, memory requirements, and processor utilization. Dataflow schedule graphs (DSGs) provide a formal abstraction for representing schedules in dataflow-based design processes. The DSG abstraction allows designers to model a schedule as a separate dataflow graph, thereby providing a formal, abstract (platform and language-independent) representation for the schedule. In this presentation, we review the DSG representation, and introduce a design methodology for embedded SPML systems that is based on explicit specifications of application graphs and schedules as cooperating dataflow models. We also develop new software synthesis techniques for automatically deriving efficient implementations from these coupled application and schedule models. We demonstrate the proposed methodology and software synthesis techniques through various experiments, including an example involving real time detection of people and vehicles using acoustic and seismic sensors.`
  },
  {
    id: "7",
    name:"Tushar Vrind",
    designation:"Senior Technical Director",
    university:"Samsung Semiconductor India R&D (SSIR)",
    bio:`Tushar Vrind is a Senior Technical Director at Samsung Semiconductor India R&D (SSIR). He is a member of the Technical Ladder and a past chair of the Communication & Connectivity Center of Excellence at SSIR. He has over 25 years of professional experience in wireless communication (2G to 5G) and the embedded domain, particularly with the Exynos System on Chip (SoC) at Samsung Electronics. He has over 50 applied patents and more than 30 granted patents worldwide in the areas of embedded systems and wireless protocols. He has co-authored over 40 technical contributions, papers, and journal articles with 3GPP and IEEE. Tushar is a notable innovator, intrapreneur, and technology evangelist at SSIR. He is also a Senior Member of IEEE and a past Executive Committee member of the IEEE ComSoc Bangalore Chapter. He has contributed as a TPC member at several IEEE conferences. His research interests include wireless networking, cellular communication, medium access protocols, resource allocation protocols, applications of machine and deep learning, and real-time operating systems. He holds a bachelor's degree in Computer Engineering from Birla Institute of Technology, Mesra, India, and a Master of Science (Research) in Wireless Communication and Networks from the International Institute of Information Technology, Bangalore, India. He also participated in Stanford Ignite, a certification program in Entrepreneurship and Innovation from the Graduate School of Business, Stanford University.`,
    imageUrl: "/TusharVrind.jpg",
    title: "Aerial Edge Intelligence: Algorithms, Protocols, and Deployment Strategies for 6G Non-Terrestrial Networks",
    about:`As 6G networks evolve, Non-Terrestrial Networks (NTNs) powered by Unmanned Aerial Vehicles (UAVs) are emerging as a critical enabler of global connectivity. This talk provides an in-depth exploration of the algorithms, protocols, and deployment strategies necessary for efficient aerial communication. We will discuss key challenges such as dynamic management, energy-efficient operation, and real-time adaptation in time-varying environments. Additionally, we will cover optimization techniques for data transmission, network selection, and seamless integration of aerial platforms with terrestrial infrastructure. By addressing both theoretical and practical aspects, this session offers a comprehensive roadmap for deploying UAV-assisted communication in next-generation wireless networks.`
  },
  {
    id: "8",
    name:"Ujjwal Maulik",
    designation:"Professor",
    university:"Dept. of Comp. Sc. and Engg., Jadavpur University",
    bio:`Dr. Ujjwal Maulik is a Professor in the Dept. of Comp. Sc. and Engg., Jadavpur University since 2004. He was also the former Head of the same Department. He also held the position of the Principal in charge and the Head of the Dept. of Comp. Sc. and Engg., Kalayni Govt. Engg. College. Dr. Maulik has worked in many universities and research laboratories around the world as visiting Professor/ Scientist including Los Alamos National Lab., USA in 1997, Univ. of New South Wales, Australia in 1999, Univ. of Texas at Arlington, USA in 2001, Univ. of Maryland at Baltimore County, USA in 2004,  Fraunhofer Institute for Autonome Intelligent Systems, St. Augustin, Germany in 2005, Tsinghua Univ., China in 2007, Sapienza Univ., Rome, Italy in 2008, Univ. of Heidelberg, Germany in 2009, German Cancer Research Center (DKFZ), Germany in 2010, 2011 and 2012,  Grenoble INP, France in 2010, 2013 and 2016, University of Warsaw in 2013 and 2019, University of Padova, Italy in 2014 and 2016, Corvinus University, Budapest, Hungary in 2015 and 2016,  University of Ljubljana, Slovenia in 2015 and 2017, International Center for Theoretical Physics (ICTP), Trieste, Italy in 2014, 2017 and 2018. He is the recipient of Alexander von Humboldt Fellowship during 2010, 2011 and 2012 and Senior Associate of ICTP, Italy during 2012-2018 and Fulbright Fellowship in 2024-2025. He is the Fellow of  Indian National Academy of Engineers (INAE), India, National Academy of  Science India (NASI), International Association for Pattern Recognition (IAPR),  USA, The Institute of Electrical and Electronics Engineers (IEEE), USA and Asia-Pacific Artificial Intelligence Association (AAIA), Hongkong. He is also the Distinguish Member of  the ACM. He is a Distinguish Speaker of IEEE as well as  ACM. His research interest include  Machine Learning, Pattern Analysis,  Data Science, Bioinformatics, Multi-objective Optimization, Social Networking, IoT and Autonomous Car. In these areas he has published ten books, more than four hundred papers, mentoring several start-ups, filed several patents and  already guided twenty five doctoral students. His other interest include mentoring young students, traveling extensively around the globe, outdoor Sports and  Music. `,
    imageUrl: "/UjjwalMaulik.jpg",
    title:"Machine Learning for Healthcare ",
    about:`In this lecture first we will discuss the current trends and challenges in Artificial Intelligence (AI) and  Machine Learning (ML). In addition to the fundamentals of ML, we will demonstrate the importance of using Deep Learning (DL), Graph neural network (GNN) and explainable AI. While DL has been used very successfully for image analysis, GNN is being used extensively for unstructured datasets including  biological datasets available in the form of graphs containing the interaction between genes, drugs, diseases etc. 

ML is used in healthcare with the goal for betterment in therapeutic as well as early diagnosis of diseases. Moreover, generally the same therapies are used for patients having similar diseases. However, based on the biological conditions of a patient, use of specific therapy is the key in precision medicine. In the second part of the lecture we will discuss how DL and GNN techniques can be used for developing improved healthcare systems. The explainable AI will also be discussed to address the practical challenges in the medical expert system.   

Finally we will also discuss how Data Science and ML together is changing the research and development road map. These are both advantages and disadvantages of using sophisticated ML techniques. We will discuss the challenges in detail. 
`
  },
  {
    id: "9",
    name:"David W. Matolack",    
    designation:"Professor",
    university:"University of South Carolina",
    bio:"David W Matolak received the BS degree from The Pennsylvania State University, MS degree from The University of Massachusetts, and PhD degree from The University of Virginia, all in electrical engineering. He has over 25 years’ experience in communication system research, development, and deployment, with industry, government institutions, and academia, including AT&T Bell Labs, L3 Communication Systems, MITRE, and Lockheed Martin. He has over 250 refereed publications and ten patents. He was a professor at Ohio University (1999-2012), and since 2012 has been a professor at the University of South Carolina. He has been Associate Editor for several IEEE journals, is currently the chair of the IEEE VTS Propagation Committee, and has delivered several dozen invited presentations at a variety of international venues. His research interests are radio channel modeling, communication techniques for non-stationary fading channels, and secure and covert communications. Prof. Matolak is a Fellow of the IEEE, a member of standards groups in RTCA and ITU, and a member of Eta Kappa Nu, Sigma Xi, Tau Beta Pi, URSI, ASEE, AAAS, and AIAA.",
    imageUrl: "/DavidMatolak.jpg",
    title:"Reliable Future Aviation Communications",
    about:"Growth in aviation will require advances in air-ground and air-air communications, navigation, and surveillance (CNS). Projects such as NASA’s Advanced Air Mobility (AAM), which is aimed at the transportation of both cargo and people in low-altitude flights in and around urban areas, require extremely high-reliability links, often with low latencies. In this presentation, we provide background on aviation trends and estimated aviation link quality requirements, briefly discuss AAM system requirements, then focus on reliable air-ground (AG) communications. For this we discuss both intrinsic challenges such as wireless channel impairments and spectrum constraints, as well as extrinsic challenges such as interference, both unintentional and intentional (i.e., jamming). We summarize reliability techniques at the network and data link layers, then turn to the physical layer, and discuss in some detail AG channel effects, transmission security (transec), and anti-jam (AJ) techniques. We illustrate that by taking an adversary’s perspective we can improve link design and operation. The talk will conclude with comments on the future potential of machine learning and artificial intelligence, along with other areas for future work."
  }

];
